apiVersion: v1
kind: Secret
metadata:
  name: heroes-secret
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
data:
  # 'echo -n "egsmartin" | base64'
  username: ZWdzbWFydGlu
  password: VmVyYTE1MTE=

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heroes
secrets:
- name: heroes-secret