apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: heroes-svc-dr
spec:
  host: heroes-svc
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: grupo1
    labels:
      version: v1
  - name: grupo2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN