apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  namespace: knative-serving
data:
  container-concurrency-target-default: "100"
  container-concurrency-target-percentage: "0.7"
  enable-scale-to-zero: "true"
  max-scale-up-rate: "10"
  max-scale-down-rate: "2"
  panic-window: "6s"
  panic-window-percentage: "10" 
  panic-threshold-percentage: "200"
  target-burst-capacity: "200"
  requests-per-second-target-default: "200"
  scale-to-zero-grace-period: "30s"
  stable-window: "60s"
  tick-interval: "2s"
  enable-vertical-pod-autoscaling: "false"