apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: heroes-svc
  namespace: heroes-kn-ns
spec:
  traffic:
  - revisionName: heroes-svc-sw49d
    name: v2
    percent: 60
  - revisionName: heroes-svc-rnlw4
    name: v1
    percent: 40
#http://heroes-svc.heroes-kn-ns/heroes
#http://v1-heroes-svc.heroes-kn-ns/heroes
#http://v2-heroes-svc.heroes-kn-ns/heroes
---
apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: heroes-last-svc
  namespace: heroes-kn-ns
spec:
  traffic:
  - configurationName: heroes-svc
    percent: 100

#http://heroes-last-svc.heroes-kn-ns/heroes
