apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: heroes-svc
  namespace: heroes-kn-ns
spec:
  traffic:
  - configurationName: heroes-svc-00001
    name: v1
    percent: 70
  - configurationName: heroes-svc-00002
    name: v2
    percent: 30
