apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: heroes-svc
  namespace: heroes-kn-ns
spec:
  template:
    spec:
      serviceAccountName: build-bot
      containers:
      - name: heroes
        image: egsmcontenedor.azurecr.io/hello-jib:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
