apiVersion: serving.knative.dev/v1
kind: Route
metadata:
  name: heroes-svc
  namespace: default
spec:
  traffic:
  - revisionName: heroes-svc-k9fch
    percent: 60
    tag: v1
  - revisionName: heroes-svc-bmkjg
    percent: 40
    tag: v2
#http://heroes-svc.default/heroes
#http://v1.heroes-svc.default/heroes
#http://v2.heroes-svc.default/heroes
---
apiVersion: serving.knative.dev/v1
kind: Route
metadata:
  name: heroes-last-svc
  namespace: default
spec:
  traffic:
  - configurationName: heroes-last-svc
    percent: 100
    tag: latest

#http://heroes-last-svc.default/heroes
