apiVersion: v1
kind: Namespace
metadata:
  name: heroes-kn-ns
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: heroes-kn-ns
secrets:
- name: milocalregistry
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ3d3cuZ3ouY29tOjUwMDAiOnsidXNlcm5hbWUiOiJlZ3NtYXJ0aW4iLCJwYXNzd29yZCI6IlZlcmExNTExIiwiYXV0aCI6IlpXZHpiV0Z5ZEdsdU9sWmxjbUV4TlRFeCJ9fX0=
kind: Secret
metadata:
  name: milocalregistry
  namespace: heroes-kn-ns
type: kubernetes.io/dockerconfigjson
