apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes
  namespace: heroes-ns
  labels:
    app: heroes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
      - name: heroes
        image: www.gz.com:5000/hello-jib:0.0.1-SNAPSHOT
        ports:
        - name: http  
          containerPort: 8082
        livenessProbe:
          httpGet:
            path: /heroes
            port: 8082
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /heroes
            port: 8082
          initialDelaySeconds: 0
          timeoutSeconds: 1          
      imagePullSecrets:
      - name: milocalregistry          