apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes
  labels:
    app: heroes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
      - name: heroes
        image: www.gz.com:5000/hello-jib:0.0.1-SNAPSHOT
        ports:
        - name: http  
          containerPort: 8082
      imagePullSecrets:
      - name: milocalregistry          